// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1eQulGy6hNAVpUlusi7bIjhwBwq9alE4',
    appId: '1:432512488540:web:c8417db5f3a29eaa11c299',
    messagingSenderId: '432512488540',
    projectId: 'chatapptute-3a9ad',
    authDomain: 'chatapptute-3a9ad.firebaseapp.com',
    storageBucket: 'chatapptute-3a9ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8U-q9n8mdqV43cvAjDiA_NMBXjChsET0',
    appId: '1:432512488540:android:44275a7dc67d867c11c299',
    messagingSenderId: '432512488540',
    projectId: 'chatapptute-3a9ad',
    storageBucket: 'chatapptute-3a9ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDbDnbOxj0Hp7FZwlegMdz7jpiR4m0j1k',
    appId: '1:432512488540:ios:86ca14ddea8709ca11c299',
    messagingSenderId: '432512488540',
    projectId: 'chatapptute-3a9ad',
    storageBucket: 'chatapptute-3a9ad.appspot.com',
    iosBundleId: 'com.example.demo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDbDnbOxj0Hp7FZwlegMdz7jpiR4m0j1k',
    appId: '1:432512488540:ios:aab3abd4d3af751e11c299',
    messagingSenderId: '432512488540',
    projectId: 'chatapptute-3a9ad',
    storageBucket: 'chatapptute-3a9ad.appspot.com',
    iosBundleId: 'com.example.demo1.RunnerTests',
  );
}
